name: Temporal Integration Test
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  tests:
    name: "Integration testing"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Set up temporal environment"
        run: docker compose -f docker-compose/ci-temporal-dependencies.yml up -d
      - name: "Test against temporal"
        run: make ci-temporal-integ-test
      - name: Dump docker logs
        if: always()
        uses: jwalton/gh-docker-logs@v2
      - name: Go Coverage Badge
        uses: tj-actions/coverage-badge-go@v1
        with:
          filename: coverage.out

      - uses: stefanzweifel/git-auto-commit-action@v4
        id: auto-commit-action
        with:
          commit_message: Apply Code Coverage Badge
          skip_fetch: true
          skip_checkout: true
          file_pattern: ./README.md

      - name: Push Changes
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}
          branch: ${{ github.ref }}